name: Push Workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: echo "Hello, you pushed a commit"
      - name: Get coode
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Print goodbye
        run: echo "Job done, goodbye"
